version: '2.1'

orbs:
  ruby: circleci/ruby@2.1.4
jobs:
  test:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - run:
          command: cd ruby; bundle exec ruby main.rb
workflows:
  test:
    jobs:
      - test
